### ISSUE TITLE
glibc for termux compile libhybris，run test_egl tls error

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#114]
### Problem description

test_egl libhybris is compiled through glibc for termux, there will be a tls conflict, and the android library cannot be modified, is there a way to call the android native library by modifying glibc for termux with libhybris implementation

### System information

termux-info:
```
```

**Comment by Maxython** [comment]
Write in more detail: how you compiled it;  what error does it give;  which glibc packages do you use (from `gpkg` or from `gpkg-dev`)?

**Comment by szllzs** [comment]
gpkg-dev


grun --shell
cd ~/libhybris/hybris/
./autogen.sh --with-android-headers=/data/data/com.termux/files/home/libhybris/android-header --prefix=/data/data/com.termux/files/usr/glibc --enable-arch=arm64 --enable-initialize-bionic
make

**Comment by szllzs** [comment]
glibc tls and bionic tls conflict

**Comment by Maxython** [comment]
Unfortunately, I can't compile it (I use glibc packages from gpkg and apparently I need a glibc-based wayland). But I assume that this is a bug in libhybris itself.
