### ISSUE TITLE
[Package]: libllvm

### ISSUE THREAD

**Issue by askorbinovaya-kislota** [termux-pacman/glibc-packages#129]
### Why is it worth to add this package?

mesa's llvmpipe and zink depend on this, and wine depends on mesa for displaying graphics

### Home page URL

https://llvm.org/

### Source code URL

https://github.com/llvm/llvm-project

### Packaging policy acknowledgement

- [x] I have read the Termux-Pacman [Package Addition Policy](https://github.com/termux-pacman/glibc-packages/wiki/Package-Addition-Policy) and understand that my request will be denied in case of violation.

### Additional information

builds fine with archlinux pkgbuild (but the version is ancient, 15.0.7)

**Comment by romanovj** [comment]
zink doesn't need libllvm
