### ISSUE TITLE
[Package]: alsa-lib

### ISSUE THREAD

**Issue by eirkkk** [termux-pacman/glibc-packages#141]
### Why is it worth to add this package?

Dependencies pulseaudio

### Source code URL

https://github.com/alsa-project/alsa-lib

### Packaging policy acknowledgement

- [X] I have read the Termux-Pacman [Package Addition Policy](https://github.com/termux-pacman/glibc-packages/wiki/Package-Addition-Policy) and understand that my request will be denied in case of violation.

### Additional information

Dependencies pulseaudio

**Comment by romanovj** [comment]
build with
`-D alsa=disabled`

because https://github.com/termux/termux-packages/issues/17692#issuecomment-1690419567
