### ISSUE TITLE
[Question]: why python is not enabled

### ISSUE THREAD

**Issue by 500InternalError** [termux-pacman/glibc-packages#150]
### Problem description

I want to try to compile gobject-introspection which seems requires python. May I ask why it is disabled and how could I get it?(cant manage to cross compile python on my computer)

### System information

termux-info:
```
```

**Comment by Maxython** [comment]
> I want to try to compile gobject-introspection which seems requires python. May I ask why it is disabled and how could I get it?

Because when added, `python 3.12` was planned. But this version did not compile correctly and did not pass the test. The current plan is to add `python 3.11.6` along with `python-pip`.

> (cant manage to cross compile python on my computer)

You can try to compile it on your Termux device, it will be easier there.

**Comment by 500InternalError** [comment]
Thx. But why not just release the 3.11.5 version? I mean even arch is using 3.11.5, and it saves a lot of time to have a pre-built binary.
