### ISSUE TITLE
Box86

### ISSUE THREAD

**Issue by BloodANGELdb** [termux-pacman/glibc-packages#162]
I installed glibc in termux, installed Box64 and the binary was working, I also tried to compile it myself and everything worked, well, I can’t figure out how to compile or install Box86, all attempts end in compilation errors, and when installing a ready-made Box86 from the pacman repository there is an error (the architecture is not suitable)  .  Please tell me the solution to this problem.

**Comment by Maxython** [comment]
> I can’t figure out how to compile or install Box86, all attempts end in compilation errors, and when installing a ready-made Box86 from the pacman repository there is an error (the architecture is not suitable)

`box86` will work and compile only on `arm` (`armv7h`). For understanding, in the official [box86 repo](https://github.com/ptitSeb/box86) there is a full warning that it is only for ARM:
>> *You NEED a 32-bit subsystem to run and build Box86. Box86 is useless on 64-bit only systems. Also, you NEED a 32-bit toolchain to build Box86. A toolchain that only supports 64-bit will not compile Box86, and you'll get errors (typically on aarch64, you get "-marm" not recognized, and you'll need a multiarch or chroot environment).*

No wonder you only have errors.

> Please tell me the solution to this problem.

The existing solution is to switch from `aarch64 glibc` to `arm glibc`, but then `box64` will not work. A more correct way is to compile `glibc32` (glibc on arm for aarch64) which will allow you to run arm binaries on an aarch64 device.
