### ISSUE TITLE
[Bug]: shm_open failed!

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#190]
### Problem description

#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/mman.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
 
#define MMAP_DATA_SIZE 1024
 
#define USE_MMAP 1
 
int main(int argc,char * argv[])
{
        char * data;
        int fd = shm_open("shm-file0001", O_CREAT|O_RDWR, 0777);
 
        if (fd < 0) {
                printf("shm_open failed!\n");
                return -1;
        }
 
        ftruncate(fd, MMAP_DATA_SIZE);
        if (USE_MMAP) {
                data = (char*)mmap(NULL, 1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
                if (!data) {
                        printf("mmap failed\n");
                        close(fd);
                }
 
 
                sprintf(data, "This is a share memory! %d\n", fd);
 
                munmap(data, MMAP_DATA_SIZE);
        }
        else {
            char buf[1024];
            int len = sprintf(buf,"This is a share memory by write! ! %d\n",fd);
            if (write(fd, buf, len) <= 0) {
                printf("write file %d failed!%d\n",len,errno);
             }  
        }
 
        close(fd);
        getchar();
 
        shm_unlink("shm-file0001");
 
        return 0;
}

### System information

termux-info:
```
```
0.118 arrch64

**Comment by Maxython** [comment]
What do you mean by "shm_open failed"? What error did you notice?

I checked your script and all functions work.

Also, please send the result of the `termux-info` command so that i can understand your full-fledged environment in Termux.

**Comment by szllzs** [comment]
grun --shell
gcc writer.c -o writer
./writer

**Comment by Maxython** [comment]
It looks like either you have an old `glibc` or you are looking in the wrong place. It should be noted that the `shm_open` function creates a file in `/data/data/com.termux/files/usr/tmp` since all Android devices do not have a `/dev/shm` directory. Try updating `glibc` and running your code, but this time check the file in `/data/data/com.termux/files/usr/tmp`.
