### ISSUE TITLE
[Bug]: termux 0.118 arrch64 install error

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#20]
### Problem description

Warning reported while extracting /data/data/com.termux/files/usr/glic/bin/gcc-ranlib during the installation of arrch glibc-for-termux on termux 0.118 arch64. This has caused the failure in running grun --shell and some files were not installed to the glibc directory.
![warn](https://github.com/termux-pacman/glibc-packages/assets/13085785/e7128cec-9b4c-4478-a58e-80018a092808)

### System information

termux-info:
```
```

**Comment by Maxython** [comment]
Based on your screenshot, I'm assuming that you have installed glibc packages from a release that were compiled on a linux distribution. For these packages, you must use `proot --link2symlink` during installation ([more info](https://github.com/termux-pacman/glibc-packages/blob/main/README-old.md#installation-steps)).

And I recommend using the glibc packages from the `gpkg-dev` repo (note: the Termux-Pacman service is not available at the moment - https://github.com/termux-pacman/termux-packages/issues/9)
