### ISSUE TITLE
[Bug]: Bad system call in accept function on termux, when use glibc for termux

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#21]
### Problem description

the error occurred when running server.c using the glib for termux native package and GCC compiler. The program crashes with this error because accept method throws it internally. The error is always present and consistent every time the program is run.

This is a demo that is certain to occur. 
`#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdlib.h>
#include <getopt.h>

//#define PORT 9988
void printf_usage(char *progname)
{
	printf("%s usage: \n",progname);
	printf("-p(--port): sepcify server port \n");
	printf("-h(--help): print this help information \n");
}

int main(int argc, char **argv)
{
	int			socket_fd = -1, client_fd = -1;
	int			rv = -1, rv1 = -1;
	struct sockaddr_in 	serveraddr, clientaddr;
	char			buf[1024];
	socklen_t		clientaddr_len = sizeof(struct sockaddr);
	int			port;
	int			ch;
	int			index;
	struct	option		opts[] = {
		{"port", required_argument, NULL, 'p'},
		{"help", no_argument, NULL, 'h'},
		{NULL, 0, NULL, 0}
	};

	while((ch = getopt_long(argc, argv, "p:h", opts, NULL)) != -1)
	{
		switch(ch)
		{
			case 'p':
				port = atoi(optarg);
				break;

			case 'h':
				printf_usage(argv[0]);
				return 0;
		}
	}

	while(argc < 2)
	{
		printf("please input %s [port] \n",argv[0]);
		return -1;
	}

	socket_fd = socket(AF_INET, SOCK_STREAM, 0);
	if(socket_fd < 0)
	{
		printf("create socket failure : %s \n", strerror(errno));
		return -2;
	}

	port = atoi(argv[1]);
	serveraddr.sin_family =	AF_INET;
	serveraddr.sin_port =	htons(port); //操作系统的字节序为小端，所以需要转换成网络大端字节序
	serveraddr.sin_addr.s_addr = htonl(INADDR_ANY);	//ip地址为4个字节，用htonl；INADDR_ANY（实际上是0）可以自动选择服务器的ip，使用有线网卡就用有线ip，使用无线网卡就用无线ip。
	if(bind(socket_fd, (struct sockaddr *)&serveraddr, sizeof(serveraddr)) < 0)
	{
		printf("create server failure : %s \n", strerror(errno));
		return -3;
	}
	printf("socket [%d] bind on port[%d] for all IP address succesfully !", socket_fd, port);

	listen(socket_fd, 10); //监听socket，等待客户端连接，10为正在连接服务端的最大数，超过就不能连入服务器。

	while(1)
	{
		printf("\n Start waiting and accept new client connect...\n");
		client_fd = accept(socket_fd, (struct sockaddr *)&clientaddr, &clientaddr_len); //一般来说不关心addr的长度大小，这个数据不重要；地址为ipv4类型，需要保持一致；内核返回的值为新的socket描述符，用来服务某个接入的客户端。
		if(client_fd < 0)
		{
			printf("accept new socket failture : %s\n", strerror(errno));
			return -4;
		}
		printf("accept new client[%d] socket[%s:%d]\n",client_fd, inet_ntoa(clientaddr.sin_addr), ntohs(clientaddr.sin_port));//inet_ntoa函数为整型转字符型，ntohs函数为大端转小端。
		while(1)
		{
			memset(buf, 0, sizeof(buf));
			rv = read(client_fd, buf, sizeof(buf));
			if(rv < 0)
			{
				printf("read data from client [%d] failure : %s\n", client_fd, strerror(errno));
				close(client_fd);
				break;
			}
			else if(rv == 0)
			{
				printf("%d \n",rv);
				printf("client [%d] disconnected \n", client_fd);
				close(client_fd);
				break;	
			}
			printf("read %d bytes data from client[%d] and the data is : %s \n", rv , client_fd, buf);
		
			rv1 = write(client_fd, buf, rv);
			if(rv1 < 0)
			{
				printf("write data back to client[%d] failure: %s \n", client_fd, strerror(errno));
				close(client_fd);
				break;
			}
		}
		sleep(1);
	}
	close(socket_fd);
}`

![server c](https://github.com/termux-pacman/glibc-packages/assets/13085785/da0e9423-5b62-4bbb-b03a-20a73b4d2711)
![Screenshot_2023-05-28-16-30-18-10_84d3000e3f40171](https://github.com/termux-pacman/glibc-packages/assets/13085785/f27c0834-d124-4888-942a-b1308f70560b)
![Screenshot_2023-05-28-16-30-52-72_84d3000e3f40171](https://github.com/termux-pacman/glibc-packages/assets/13085785/377d47f3-5276-405d-80e2-5a579a1ebc25)
![Screenshot_2023-05-28-16-32-50-67_84d3000e3f40171](https://github.com/termux-pacman/glibc-packages/assets/13085785/53d06299-3dff-4236-a1bb-1d971374be5b)

### System information

termux-info:
```0.118 arrch64
```[glibc packages for termux 2022-07-11](https://github.com/termux-pacman/glibc-packages/releases/tag/20220711)

**Comment by Maxython** [comment]
Try using the glibc packages from the [gpkg-dev](https://github.com/termux-pacman/glibc-packages#code-for-connecting-repository) repo. Once connected, run the following command to install all packages from the gpkg-dev repo:
```
pacman -Sy gpkg-dev
```

**Comment by szllzs** [comment]
> Try using the glibc packages from the [gpkg-dev](https://github.com/termux-pacman/glibc-packages#code-for-connecting-repository) repo. Once connected, run the following command to install all packages from the gpkg-dev repo:
> 
> ```
> pacman -Sy gpkg-dev
> ```

No effect, still reporting an error
![Screenshot_2023-05-29-10-57-15-92_84d3000e3f4017145260f7618db1d683](https://github.com/termux-pacman/glibc-packages/assets/13085785/8494767b-3fea-4292-85aa-2544bce4d470)

**Comment by Maxython** [comment]
Hm, ok. I will ask you to do the following:
- Run the following command and post the result: `strace ./server1`
- Send a link to the source code of this program.

**Comment by szllzs** [comment]
![1](https://github.com/termux-pacman/glibc-packages/assets/13085785/cfa0174e-aa31-47ac-ab36-4539fc9616e5)
![2](https://github.com/termux-pacman/glibc-packages/assets/13085785/54c4a5c4-7f9d-4e47-83c9-3ccbf3c07849)

Source code is above.

**Comment by Maxython** [comment]
The screenshot shows that the error is caused by the `accept` system call, which is rather strange since this system call is in the [SYSCALLS.TXT](https://android.googlesource.com/platform/bionic/+/android-4.2.2_r1/libc/SYSCALLS.TXT#235) list.

Try running your binary with `proot`:
```
proot ./server1 10000
```

**Comment by szllzs** [comment]
proot is ok,termux native is bad

**Comment by Maxython** [comment]
The problem is still not solved, you need to make everything work without `proot`.
