### ISSUE TITLE
Compile Glibc

### ISSUE THREAD

**Issue by BloodANGELdb** [termux-pacman/glibc-packages#216]
Can I compile glibc_arch64 so that the prefix is ​​for example /data/data/com.termux/files/usr/glibb?  all my attempts are unsuccessful, glibc compiles well, I get a bad system call

**Comment by Maxython** [comment]
Why would you want to compile glibc with a different prefix?

So I understand that you tried to compile glibc without patches, because you are getting bad system calls. This is incorrect because glibc by default is not configured to work in the android Termux application.

**Comment by Maxython** [comment]
You can compile glibc with a different prefix using `build-package.sh`, but with one change:
```diff
--- a/scripts/build/termux_step_setup_variables.sh
+++ b/scripts/build/termux_step_setup_variables.sh
@@ -36,7 +36,7 @@ termux_step_setup_variables() {
        fi

        if [ "$TERMUX_PACKAGE_LIBRARY" = "glibc" ]; then
-               export TERMUX_PREFIX="$TERMUX_PREFIX/glibc"
+               export TERMUX_PREFIX="$TERMUX_PREFIX/test-glibc"
                if ! package__is_package_name_have_glibc_prefix "$TERMUX_PKG_NAME"; then
                        TERMUX_PKG_NAME="$(package__add_prefix_glibc_to_package_name ${TERMUX_PKG_NAME})"
                fi
```

To start glibc compilation you must run the following command:
```
./build-package.sh -s -f --library glibc gpkg/glibc
```

**Comment by BloodANGELdb** [comment]
> To start glibc compilation you must run the following command:
> ```
> ./build-package.sh -s -f --library glibc gpkg/glibc
> ```

Thanks a lot.  I'm sorry, but I don't fully understand how to do this?  What procedure should be followed to use build-package?

**Comment by BloodANGELdb** [comment]
> # starting the compiler
> ./build-package.sh -s -f --library glibc gpkg/glibc
> 
> # the final package will be stored in the output folder
> ls ./output
> ```

![Screenshot_2024-03-21-15-07-06-061_com.termux-edit.jpg](https://github.com/termux-pacman/glibc-packages/assets/44096076/6a0d5dbe-2e0d-4354-a579-6c1e1ba9f409)

I tried this but I get these errors

**Comment by BloodANGELdb** [comment]
> ```diff
> --- a/scripts/build/termux_step_setup_variables.sh
> +++ b/scripts/build/termux_step_setup_variables.sh
> @@ -36,7 +36,7 @@ termux_step_setup_variables() {
>         fi
> 
>         if [ "$TERMUX_PACKAGE_LIBRARY" = "glibc" ]; then
> -               export TERMUX_PREFIX="$TERMUX_PREFIX/glibc"
> +               export TERMUX_PREFIX="$TERMUX_PREFIX/test-glibc"
>                 if ! package__is_package_name_have_glibc_prefix "$TERMUX_PKG_NAME"; then
>                         TERMUX_PKG_NAME="$(package__add_prefix_glibc_to_package_name ${TERMUX_PKG_NAME})"
>                 fi
> ```


compilation succeeds if export TERMUX_PREFIX="$TERMUX_PREFIX/glibc" .  but as soon as I change this line to export TERMUX_PREFIX="$TERMUX_PREFIX/glibc-test" I get the following error

**Comment by Maxython** [comment]
I double-checked what needed to be configured in the compiler and created a patch. To use it you need to put it in your repo and perform the following steps:
```bash
./get-build-package.sh
git apply < change_prefix.txt
```
The patch itself:  [change_prefix.txt](https://github.com/termux-pacman/glibc-packages/files/14721721/change_prefix.txt)

**Comment by BloodANGELdb** [comment]
> I double-checked what needed to be configured in the compiler and created a patch. To use it you need to put it in your repo and perform the following steps:

Thanks, now the compilation ends with this error

![Screenshot_2024-03-22-13-50-02-441_com.termux-edit.jpg](https://github.com/termux-pacman/glibc-packages/assets/44096076/90e942d1-2a67-476f-9e2e-7f5432b676af)

**Comment by BloodANGELdb** [comment]
Thank you very much, everything worked out)
