### ISSUE TITLE
locale is invalid

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#24]
### Problem description

export LANG=zh_CN.UTF-8;

Running multilingual software still displays an English interface.

### System information

termux-info:
```118
```gpkg-dev

**Comment by Maxython** [comment]
Can you tell me what command you used and is it glibc based? The glibc locale only works with glibc-based programs.

**Comment by szllzs** [comment]
> Can you tell me what command you used and is it glibc based? The glibc locale only works with glibc-based programs.

It seems that the glibc for termux does not have the "LANGUAGE" field in its locale, while a normal Linux system's locale does have this field. This causes an issue where setting "export LANGUAGE=zh_CN.UTF-8" works with Wine8.9 on Linux Ubuntu, but does not have any effect with glibc for termux.

**Comment by szllzs** [comment]
It's that I didn't generate zh_CN with locale-gen
