### ISSUE TITLE
[Package]: Gallium Freedreno 

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux-pacman/glibc-packages#281]
### Why is it worth to add this package?

For opengl game in adreno & it better than Zink 

### Source code URL 1 patch 
https://github.com/xMeM/termux-packages/commit/57b1bb44c9eed341c700105efed93f9fd8bc34a6

### Source code URL 2 patch
https://gitlab.freedesktop.org/Pipetto-crypto/mesa/-/tree/freedreno?ref_type=heads

### Packaging policy acknowledgement

- [X] I have read the Termux-Pacman [Package Addition Policy](https://github.com/termux-pacman/glibc-packages/wiki/Package-Addition-Policy) and understand that my request will be denied in case of violation.

### Additional information

![Screenshot_2024-08-24-14-56-30-34_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/f99ef8a6-1bb4-467e-9834-8fe9f17ad7b8)
![Screenshot_2024-08-24-11-25-45-36_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/96cca784-85bf-4cfc-bbde-33a4a2c8eeba)

Freedreno compiled package for glibc 
[freedreno-glibc.tar.gz](https://github.com/user-attachments/files/16741992/freedreno-glibc.tar.gz)

**Comment by EDLLT** [comment]
> ### Why is it worth to add this package?
> For opengl game in adreno & it better than Zink
> 
> ### Home page URL
> _No response_
> 
> ### Source code URL 1 patch
> [xMeM/termux-packages@57b1bb4](https://github.com/xMeM/termux-packages/commit/57b1bb44c9eed341c700105efed93f9fd8bc34a6)
> 
> ### Source code URL 2 patch
> https://gitlab.freedesktop.org/Pipetto-crypto/mesa/-/tree/freedreno?ref_type=heads
> 
> ### Packaging policy acknowledgement
> * [x]  I have read the Termux-Pacman [Package Addition Policy](https://github.com/termux-pacman/glibc-packages/wiki/Package-Addition-Policy) and understand that my request will be denied in case of violation.
> 
> ### Additional information
> ![Screenshot_2024-08-24-14-56-30-34_84d3000e3f4017145260f7618db1d683](https://private-user-images.githubusercontent.com/72664192/361242507-f99ef8a6-1bb4-467e-9834-8fe9f17ad7b8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDg5MjUsIm5iZiI6MTcyNTA0ODYyNSwicGF0aCI6Ii83MjY2NDE5Mi8zNjEyNDI1MDctZjk5ZWY4YTYtMWJiNC00NjdlLTk4MzQtOGZlOWYxN2FkN2I4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIwMTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjZhOWM4M2M1YmQyZTY1OTM5ZThkMDliNzBjOTk0MTczN2JhYTdkZTQ0YTFmMTRkNGIyOTZiMTU3YjFmM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4C2H7q4znHiL_VKp-lLphj1xhj9Ur1JqwponuxF20m8) ![Screenshot_2024-08-24-11-25-45-36_84d3000e3f4017145260f7618db1d683](https://private-user-images.githubusercontent.com/72664192/361242509-96cca784-85bf-4cfc-bbde-33a4a2c8eeba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDg5MjUsIm5iZiI6MTcyNTA0ODYyNSwicGF0aCI6Ii83MjY2NDE5Mi8zNjEyNDI1MDktOTZjY2E3ODQtODViZi00Y2ZjLWJiZGUtMzNhNGEyYzhlZWJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIwMTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTMyMGQ2ZTdmNjRjYmRjYTRkYTQwMmUyNzFkYjQ5NWM1NGJlYTY4OTU4YTdhNDE3NjQzOWI1MTUzM2VmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rbdhje2ZWhma490CaO0WPjqKjBOyqMtECDOo0atc2sA)
> 
> Freedreno compiled package for glibc [freedreno-glibc.tar.gz](https://github.com/user-attachments/files/16741992/freedreno-glibc.tar.gz)

The reason he's getting

> ### Why is it worth to add this package?
> For opengl game in adreno & it better than Zink
> 
> ### Home page URL
> _No response_
> 
> ### Source code URL 1 patch
> [xMeM/termux-packages@57b1bb4](https://github.com/xMeM/termux-packages/commit/57b1bb44c9eed341c700105efed93f9fd8bc34a6)
> 
> ### Source code URL 2 patch
> https://gitlab.freedesktop.org/Pipetto-crypto/mesa/-/tree/freedreno?ref_type=heads
> 
> ### Packaging policy acknowledgement
> * [x]  I have read the Termux-Pacman [Package Addition Policy](https://github.com/termux-pacman/glibc-packages/wiki/Package-Addition-Policy) and understand that my request will be denied in case of violation.
> 
> ### Additional information
> ![Screenshot_2024-08-24-14-56-30-34_84d3000e3f4017145260f7618db1d683](https://private-user-images.githubusercontent.com/72664192/361242507-f99ef8a6-1bb4-467e-9834-8fe9f17ad7b8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTA5MDksIm5iZiI6MTcyNTA5MDYwOSwicGF0aCI6Ii83MjY2NDE5Mi8zNjEyNDI1MDctZjk5ZWY4YTYtMWJiNC00NjdlLTk4MzQtOGZlOWYxN2FkN2I4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA3NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYTQxMjU3N2IzMjMxMTBiMTIwMzY3YzVhNWFlNGNkMDFlMzBlN2MzZjYxMzk1OTIxYTg3ZDE2OTk4ZmRkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6BvwmxNkoJTioCLsMbIHY488Q8S7UhFEgUvF_s4QLk) ![Screenshot_2024-08-24-11-25-45-36_84d3000e3f4017145260f7618db1d683](https://private-user-images.githubusercontent.com/72664192/361242509-96cca784-85bf-4cfc-bbde-33a4a2c8eeba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTA5MDksIm5iZiI6MTcyNTA5MDYwOSwicGF0aCI6Ii83MjY2NDE5Mi8zNjEyNDI1MDktOTZjY2E3ODQtODViZi00Y2ZjLWJiZGUtMzNhNGEyYzhlZWJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA3NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ODEwY2RkMDZkZWMyZjI5ODY0ODViNzZiNDAxZGI3ZDdkMzBiNGEyNzMwNzM2ZjgwNWNkMDQ2NTFiY2I3MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJWQRGHSkqEKrxfTKNfuPwDGFR5TjrnKzIEuRhxWUlw)
> 
> Freedreno compiled package for glibc [freedreno-glibc.tar.gz](https://github.com/user-attachments/files/16741992/freedreno-glibc.tar.gz)

How did you build this btw?
