### ISSUE TITLE
[Help]: Building Glibc 

### ISSUE THREAD

**Issue by RajDave-Dev** [termux-pacman/glibc-packages#286]
### Problem description

I want to build Glibc for a custom prefix. 
I have tried building it with the build-package.sh linux-api-headers but no luck then manually building the linux-api-headers as mentioned in the build.sh file it fails with aarch64-linux-gnu-gcc not found so I added the cgct's aarch64/bin to the path and then it gaves me Segmentation Fault (core dump).
Note I have ran the setup-cgct.sh and it's exit code was 0

### System information

Debian 
x86_64
8 gb ram

**Comment by RajDave-Dev** [comment]
Help me how to build linux-api-headers and Glibc for custom prefix

**Comment by Maxython** [comment]
Here are the commands that will allow you to compile a full-fledged glibc for your application. But please pay attention to the following: 
- The prefix (path to the glibc environment) will be `/data/data/com.andio/files/usr/glibc/`.
- In this commit there is a file that needs to be placed and rename in the glibc package sources, this is necessary because this file fixes the compilation of the package. How to do this, see the command. [fake-syscall.txt](https://github.com/user-attachments/files/16906771/fake-syscall.txt)

```shell
git clone https://github.com/termux-pacman/glibc-packages
./get-build-package.sh
# Edit only the `TERMUX_APP_PACKAGE` variable
nano scripts/properties.sh
# Before running the following command, please download the file that is pinned in this commit.
mv ${PATH_TO_fake-syscall.txt} gpkg/glibc
rm gpkg/glibc/fake-syscall.h
mv gpkg/glibc/fake-syscall.txt gpkg/glibc/fake-syscall.h
sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
sudo ./scripts/run-docker.sh

# After this command, a shell from the docker image will be launched to compile the package.
# Please note that in image docker you don't need to run scripts as root user, otherwise the compilation environment will be broken.
./scripts/setup-cgct.sh
# Install temporary glibc package and linux-api-headers to compile full glibc.
mkdir ~/tmp-glibc
cd ~/tmp-glibc
wget https://service.termux-pacman.dev/gpkg/aarch64/glibc-2.39-4-aarch64.pkg.tar.xz
wget https://service.termux-pacman.dev/gpkg/aarch64/linux-api-headers-glibc-6.9-0-aarch64.pkg.tar.xz
tar xf glibc-2.39-4-aarch64.pkg.tar.xz
tar xf linux-api-headers-glibc-6.9-0-aarch64.pkg.tar.xz
# In libc.so you should edit the prefixes for your application
nano data/data/com.termux/files/usr/glibc/lib/libc.so
mkdir -p /data/data/com.andio/files/usr/glibc/
mv data/data/com.termux/files/usr/glibc/* /data/data/com.andio/files/usr/glibc/
# Congratulations, you have installed the temporary packages
# Now you can compile a full-fledged glibc for your application
cd ~/termux-packages
./build-package.sh -s --library glibc --format pacman -a aarch64 gpkg/glibc
```

**Comment by RajDave-Dev** [comment]
I have a question, why the glibc prefix? Why not   /data/data/com.andio/files/usr/ 

And sorry
And Thanks for helping and giving much detailed help.

**Comment by Maxython** [comment]
> I have a question, why the glibc prefix? Why not /data/data/com.andio/files/usr/

This is to prevent glibc-based packages from mixing with bionic-based packages. Otherwise, everything will break.

**Comment by RajDave-Dev** [comment]
@Maxython 
Now geeting this error:
```Applying patch: unistd.h.patch
Applying patch: xstat64.c.patch
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for aarch64-linux-gnu-gcc... aarch64-linux-gnu-gcc
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether aarch64-linux-gnu-gcc accepts -g... yes
checking for aarch64-linux-gnu-gcc option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether aarch64-linux-gnu-g++ accepts -g... yes
checking for aarch64-linux-gnu-g++ option to enable C++11 features... unsupported
checking for aarch64-linux-gnu-g++ option to enable C++98 features... unsupported
checking whether aarch64-linux-gnu-g++ can link programs... no
checking for systemtap static probe support... no
configure: error: in `/tmp/.termux-build/glibc/build':
configure: error: systemtap support needs sys/sdt.h with asm support```

**Comment by Maxython** [comment]
Did you follow the instructions? If so, can you say that you did something extra to make the glibc package compile to `/tmp/.termux-build/glibc/build`, when in the docker image environment it should be `/home/builder/.termux-build/glibc/build`?

**Comment by RajDave-Dev** [comment]
Yeah, but I build this on codespace and codespace provide more storage on /tmp folder, so I bound......

**Comment by Maxython** [comment]
> Yeah, but I build this on codespace and codespace provide more storage on /tmp folder, so I bound......

To compile glibc-based packages (especially if they are going to be configured for another application), it is better to do all of this on a computer, running the commands I gave you (from the instruction). I do not use codespace, and therefore it is difficult for me to understand what capabilities there are (and I think that you are trying to run compilation in a codespace environment, not in a docker image). If you can run a docker image here, then try running all of the docker commands from the instructions, because the environment will be clear to me and it will also reduce the number of random errors.

**Comment by RajDave-Dev** [comment]
No, actually my pc don't have docker support (when I run docker the environment is broken even with simple docker run -it Ubuntu:jammy) 
So I use codespace with Ubuntu jammy and docker installed then i ran this whole Commands

**Comment by Maxython** [comment]
> If I build Glibc packages and not bionic then?

If you only intend to compile glibc-based packages, the prefix will still be the same. If you want a different prefix for glibc packages (I think without the `/glibc` path), you need to edit the [`termux_step_setup_variables.sh`](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_setup_variables.sh#L39) file.

> No, actually my pc don't have docker support (when I run docker the environment is broken even with simple docker run -it Ubuntu:jammy)

If it's not a secret, what error does your computer display when you try to run image docker?

> So I use codespace with Ubuntu jammy and docker installed then i ran this whole Commands

If you ran all the commands, I would see that the compilation occurs in the image docker environment, not in the codespace. For correct understanding, by the word image docker I mean image docker [package-builder](https://github.com/termux/termux-packages/pkgs/container/package-builder), which is launched from the script `./scripts/run-docker.sh`.

**Comment by Maxython** [comment]
> the latest error I got is: build.sh line 89: elf/ld.so exec format error.

Did you run this command from this tutorial?:
```
sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```
If yes (or after installation) it still doesn't work for you, then try running the following command:
```
sudo docker run --rm --privileged tonistiigi/binfmt --install all
```
Note that these commands do not need to be run inside the docker image environment. They need to be run in your codespace environment.

**Comment by RajDave-Dev** [comment]
I ran every command including that removing qemu command before starting/running the docker

**Comment by Maxython** [comment]
> including that removing qemu command

This is not a deletion, but an installation. If the first command has already been run, then run another second command. After that, try to run the compilation of the glibc package in the image docker environment again.

**Comment by RajDave-Dev** [comment]
I am retrying it on my friend's pc, his pc has docker support.
And the docker image of termux-packages require systemtap-sdt-dev package to fix
 sys/sdt.h not found error

**Comment by RajDave-Dev** [comment]
I do still get this error and config.log tells that `/data/data/com.termux/cgct/aarch64/include/c++/14.1.0/aarch64-linux-gnu/bits/os_defines.h:39:10: fatal error: features.h: No such file or directory` 

And 

```configure:4255: result: no
configure:4566: checking for systemtap static probe support                             configure:4583: aarch64-linux-gnu-gcc -c -std=gnu11 -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -march=armv8-a -fstack-protector-strong  conftest.c >&5                                           conftest.c:14:10: fatal error: sys/sdt.h: No such file or directory                        14 | #include <sys/sdt.h>
      |          ^~~~~~~~~~~
compilation terminated.                                                                 configure:4583: $? = 1
configure: failed program was:
| /* confdefs.h */                                                                      | #define PACKAGE_NAME "GNU C Library"                                                  | #define PACKAGE_TARNAME "glibc"
| #define PACKAGE_VERSION "(see version.h)"
| #define PACKAGE_STRING "GNU C Library (see version.h)"
| #define PACKAGE_BUGREPORT "https://sourceware.org/bugzilla/"
| #define PACKAGE_URL "https://www.gnu.org/software/glibc/"
| #define PKGVERSION "(GNU libc) "
| #define REPORT_BUGS_TO "<https://github.com/termux-pacman/glibc-packages/issues>"
| #define TIMEOUTFACTOR 1
| #define BIND_NOW 1                                                                    | #define USE_MTAG 1                                                                    | /* end confdefs.h.  */
| #include <sys/sdt.h>                                                                  | void foo (int i, void *p)
| {
|   asm ("" STAP_PROBE_ASM (foo, bar, STAP_PROBE_ASM_TEMPLATE (2)) ""
|        :: STAP_PROBE_ASM_OPERANDS (2, i, p));                                         | }                                                                                     configure:4592: result: no
configure:4598: error: in `/home/builder/.termux-build/glibc/build':
configure:4600: error: systemtap support needs sys/sdt.h with asm support```

**Comment by RajDave-Dev** [comment]
Finally we built it.
Thanks for your support my friend.
