### ISSUE TITLE
am i doing something wrong. /glibc binaries are not working. 

### ISSUE THREAD

**Issue by dhuux** [termux-pacman/glibc-packages#37]
### Problem description

![Screenshot_20230616-183440_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/a9252b35-f950-46f4-b76f-201c731a095b)

i fully switched to ``` pacman, ``` then installed needed tools by runing ``` pacman -Sy gpkg-dev. ```
all binaries in ``` /glibc/bin ``` are complaining shared libraries are missing though they are there. 

![Screenshot_20230616-183343_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/e7e44924-a7b3-47a5-bd64-e9430c5c45cd)

i'm really a newbie to all these things. i'm trying to learn things and i don't have a pc. i thought by using this, i can finally run some ``` aarch64 (ARM) Linux binaries ``` on Termux without using those slow ``` proot-distros``` 

like java here:

![Screenshot_20230616-192009_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/1acc55e5-ca36-40aa-a1dd-df7ccab51ca3)

### System information

termux-info:
```
Termux Variables:                                          TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=pacman                          TERMUX_APP_PID=29878                                       TERMUX_IS_DEBUGGABLE_BUILD=1                               TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:                                 aarch64
Subscribed repositories:                                   # /data/data/com.termux/files/usr/etc/pacman.conf
[main]                                                     Usage = All
Server = https://service.termux-pacman.dev/main/aarch64    Server = https://s3.amazonaws.com/termux-pacman.us/main/aarch64                                                       [x11]
Usage = All
Server = https://service.termux-pacman.dev/x11/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/x11/aarch64
[root]
Usage = All
Server = https://service.termux-pacman.dev/root/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/root/aarch64
[tur]
Usage = All
Server = https://service.termux-pacman.dev/tur/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur/aarch64
[tur-continuous]
Usage = All
Server = https://service.termux-pacman.dev/tur-continuous/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-continuous/aarch64
[tur-multilib]
Usage = All
Server = https://service.termux-pacman.dev/tur-multilib/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-multilib/aarch64
[gpkg-dev]
Usage = All
Server = https://service.termux-pacman.dev/gpkg-dev/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/gpkg-dev/aarch64
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
9
Kernel build information:
Linux localhost 4.4.111-22376662 #1 SMP PREEMPT Thu Sep 16 20:22:46 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A730F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.tasker versionCode:6
com.termux.window versionCode:15
```

**Comment by Maxython** [comment]
In the first case (with `gcc`), you forgot to run `grun --shell` - a customized shell so that the glibc commands can work and you have access to them.

In the second case, `java` can't start because the specified coordinate `ld-linux-aarch64.so.1` is incorrect. You must run `java` with `grun` to make it work: `grun ./java`.

**Comment by dhuux** [comment]
> In the first case (with `gcc`), you forgot to run `grun --shell` - a customized shell so that the glibc commands can work and you have access to them.
> 
> In the second case, `java` can't start because the specified coordinate `ld-linux-aarch64.so.1` is incorrect. You must run `java` with `grun` to make it work: `grun ./java`.

``` grun ./gcc ``` works! thanks. but ``` grun ./java ``` comes with this error.

![Screenshot_20230616-195830_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/9a8ab22a-a0ae-4920-902e-c82644c9dc5f)

any idea why?

**Comment by Maxython** [comment]
There are a lot of reasons why you have this error, but it came from a binary. Could you post a link to where you got the binary from?

**Comment by dhuux** [comment]
i think it was from the openjdk site. here: https://jdk.java.net/archive/
```
Linux/AArch64 | 64-bit
``` 

i think i also tried the Oracle jdk one for linux/aarch64. here: https://www.oracle.com/java/technologies/downloads/#jdk20-linux

do you think there are some linux libs that Java binaries depend on missing? if i fire up a proot distro and run the same binary it works. 

thanks for your answer.

**Comment by Maxython** [comment]
I checked `java` from two sources and they both work great. I'm confused by your expression "I think", do you know where you downloaded `java` from?

Try downloading `java` from those sources you mentioned and run it. If you get the same error, then send a screenshot of the result from the following command: `strace grun ./java`.

**Comment by dhuux** [comment]
> I'm confused by your expression "I think", do you know where you downloaded `java` from?
> 

lol. i'm really bad at English. i don't even know why i chose to use that expression two times.  

maybe i messed things up back when i was trying to make it work in Termux. 

i will download it from there again and try.

**Comment by dhuux** [comment]
bro it worked. thanks for saving me from headaches that i  inflicted onto myself.  now how can i tell other programs to use java for example gradle? is creating an alias for it the only solution?

**Comment by Maxython** [comment]
I suspect you need to create a bash script named `java` in `$PREFIX/bin` in order for java programs to use it.
```bash
#!/data/data/com.termux/files/usr/bin/bash

grun --shell *path_to_binary_java* $@
```

But that's not accurate, I'm not very versed in java.

**Comment by dhuux** [comment]
thank you bro. you are really doing great work.
aliases are kind of easy for me and they are working fine.
```
alias -s  java="$JAVA_HOME/bin && grun ./java"
alias -s  javac="$JAVA_HOME/bin && grun ./javac"
``` 
but it would be better if there is one solution for all binaries in `/bin.`
