### ISSUE TITLE
error while loading shared libraries: libdl.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#38]
### Problem description

With the elf compiled by glibc, the native run will prompt that the loading libdl.so failed, but the internal operation of the grun shell is fine

![Screenshot_2023-06-17-18-42-01-49_84d3000e3f4017145260f7618db1d683](https://github.com/termux-pacman/glibc-packages/assets/13085785/2e157cdc-360f-4001-bce5-f5263f71e734)

### System information

termux-info:
```
```

**Comment by szllzs** [comment]
In the armv7 package, this compiles the test, and termux natively runs normally

**Comment by Maxython** [comment]
This is due to the `LD_PRELOAD` system value. It points to the bionic-based library `libtermux-exec.so`, which prevents the glibc binaries from running. To fix, run the customized shell:
```bash
grun --shell
```
or clear the value of `LD_PRELOAD`:
```bash
unset LD_PRELOAD
```

**Comment by szllzs** [comment]
> This is due to the `LD_PRELOAD` system value. It points to the bionic-based library `libtermux-exec.so`, which prevents the glibc binaries from running. To fix, run the customized shell:
> 
> ```shell
> grun --shell
> ```
> 
> or clear the value of `LD_PRELOAD`:
> 
> ```shell
> unset LD_PRELOAD
> ```

I see, thank you for your guidance

**Comment by dhuux** [comment]
/
