### ISSUE TITLE
glibc-packages for termux-armv7 gcc compile cmake 3.13 Bad system call

### ISSUE THREAD

**Issue by Maxython** [termux-pacman/glibc-packages#43]
### Discussed in https://github.com/termux-pacman/glibc-packages/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **szllzs** June 18, 2023</sup>
![2](https://github.com/termux-pacman/glibc-packages/assets/13085785/f0d9c0e4-2d44-4f8b-8af2-7eda43dbdbac)

I tried the 3.17, 3.13 and 3.27 source code, but all of them produced a "bad system call" error during bootstrap or configure
</div>

**Comment by Maxython** [comment]
@szllzs, could you please send your cmake compilation steps?

**Comment by szllzs** [comment]
> @szllzs, could you please send your cmake compilation steps?

run bootstrap or configure
