### ISSUE TITLE
elf binaries that are not from gpkg-dev repo are not working when in custom shell mode. 

### ISSUE THREAD

**Issue by dhuux** [termux-pacman/glibc-packages#47]
### Problem description

i have two questions and i hope you to be patient with my unprofessional questions. because i have zero knowledge of programming or even scripting. 

i haven't started learning programming yet. just trying to be familiar with basic linux environments before i start learning things.  so while playing with it -

1. grun can launch elf binaries in my proot distro's `/usr/bin` fine, in the usual way of `grun ./file` but when i add that path to the grun file and change to --shell mode, only binaries you provided can be launched. i tried a simple program like `nushell` installed in my proot distro. so while i'm in shell mode i ldded the binary to see if ld.so is not available and shared libs are missing. but they are not missing. then i ldded your binaries, like `gcc` and it's the same. your binaries are working. so why is that? is it because `vdso` not properly mapped into the address space of these programs?

![Screenshot_20230708-184219_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/72faeb08-68e7-4e70-a4d1-f03a1473d379)

3. how can add another path that ld.so will search for shared objects. like `$ARCH_PREFIX/usr/lib.` i'm trying to use the programs downloaded with TermuxArchlinux's pacman and their shared objects are not always available in your dynamic linker's default path? if not normal way, can you add this path to it, rebuild and give it to me? 

thanks!

### System information

termux-info:
```
```

**Comment by Maxython** [comment]
> i have two questions and i hope you to be patient with my unprofessional questions. because i have zero knowledge of programming or even scripting.

It's okay. Good luck.

> grun can launch elf binaries in my proot distro's /usr/bin fine, in the usual way of grun ./file but when i add that path to the grun file and change to --shell mode, only binaries you provided can be launched. i tried a simple program like nushell installed in my proot distro. so while i'm in shell mode i ldded the binary to see if ld.so is not available and shared libs are missing. but they are not missing. then i ldded your binaries, like gcc and it's the same. your binaries are working. so why is that? is it because vdso not properly mapped into the address space of these programs?

`grun --shell` does not make all glibc based binaries work, its main purpose is to provide a shell in which the commands (which are located in `$PREFIX/glibc/bin`) are readily available and can work. The main reason why binaries from Linux distributions don't work in Termux is that the coordinates to the dynamic linker are not specified correctly.

```bash
$ # Example
$ file ./bun
./bun: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[xxHash]=3cef2b0cecae5fd9, stripped
$ ./bun
bash: ./bun: cannot execute: required file not found
$ # This error indicates that the dynamic linker was not found.
```

But it is worth noting that in the latest version of `glibc`, `grun` has a new `--set` flag that sets up the correct dynamic linker coordinates, which allows it to run without using grun (but it still needs a configured shell from `grun`).

```bash
$ pkg ins patchelf # Thanks to patchelf, customization takes place
$ grun --set ./bun
$ file ./bun
./bun: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /data/data/com.termux/files/usr/glibc/lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[xxHash]=3cef2b0cecae5fd9, stripped
```

> how can add another path that ld.so will search for shared objects. like $ARCH_PREFIX/usr/lib. i'm trying to use the programs downloaded with TermuxArchlinux's pacman and their shared objects are not always available in your dynamic linker's default path? if not normal way, can you add this path to it, rebuild and give it to me?

The simplest solution:
```bash
$ LD_LIBRARY_PATH=$PREFIX/glibc/lib:$ARCH_PREFIX/usr/lib grun ./binary
```

**Comment by dhuux** [comment]
> The simplest solution:
> 
> ```shell
> $ LD_LIBRARY_PATH=$PREFIX/glibc/lib:$ARCH_PREFIX/usr/lib grun ./binary
> ```

when i add that to grun file. it solved my problem off adding alternative lib paths. but i can't enter --shell mode anymore. `grun --shell` throws this error: `CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": "/data/data/com.termux/files/usr/glibc/lib/libc.so" has bad ELF magic` 

but `grun ./binary` works and finds shared objects from the path i wanted.  

for the programs  not working in the custom shell. i solved by changing the hardcorded dynamic loader and RPATH of my executables  with commands 
`patchelf --set-interpreter
patchelf --set-rpath`  and working fine so far.
thanks for pointing me out to this. i didn't understand this.


but ther is a problem. i patched java to work in the custom shell. gradle finds jvm but but somehow can't start the daemon's process with JVM.

but you told that gradle and java is not your thing. maybe i will start asking in Termux's subreddit.

thanks my friend.

**Comment by dhuux** [comment]
![Screenshot_20230709-164622_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/7f4ce2de-87eb-49cb-b1c1-9cfb64d60752)

**Comment by Maxython** [comment]
> when i add that to grun file. it solved my problem of adding alternative lib paths. but i can't enter --shell mode anymore. grun --shell throws this error: CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": "/data/data/com.termux/files/usr/glibc/lib/libc.so" has bad ELF magic

Well, this is not surprising since this value works for bionic based binaries as well and there is a "conflict" when specifying glibc based libraries.

> for the programs not working in the custom shell. somehow grun --set ./binary did't work for me but by changing the hardcorded dynamic loader and RPATH of my executables with these commands
patchelf --set-interpreter and patchelf --set-rpath worked.
thanks for pointing me out to this. i didn't understand this.

Have you updated `glibc` to the latest version (`2.37-8`)?  If not, then your `grun` does not support the `--set` flag. By the way, to avoid such misunderstandings, send the result of the `termux-info` command. This will allow developers to understand what programs and under what conditions you work.

> but there is a problem with gradle. i patched java to work in the custom shell. gradle finds jvm but but somehow can't start the daemon's process with JVM.

I'm not a Java pro, but I'm guessing that gradle doesn't work because of incorrectly configured system directories inside the program (like `tmp`, `lib`, `bin`, etc.).

**Comment by dhuux** [comment]
i looked around and found the problem.  the reason the Daemon process failed to start was because i didn't patch the executables that are responsible for building and starting processes `jspawnhelper` and `jspawnhelper` in `/jdk-20.0.1/lib.` i thought all binaries were in the `/bin` dir only. i never expected them to be in `/lib` dir.
![Screenshot_20230709-223257_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/eadbb91b-f592-467e-aeb2-c1bb420fbbb5)

for the `/tmp` dir problem. i set environment variable with `-Djava.io.tmpdir` and gradle working fine now.
![Screenshot_20230709-234020_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/40452110-b386-4392-8d28-4788530310ed)

thanks for your help my friend.

**Comment by dhuux** [comment]
1 other question. is there  ndk r25 or even 26  for aarch64 devices? i only found ndk r24 for Termux/aarch64 somewhere.
