### ISSUE TITLE
[Bug]: mprotect permission denied

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#49]
### Problem description

Compile the demo I provided in the termux native and proot environment, the run is success, and the run prompt compiled in the glibc environment has no permission

![testmprotect](https://github.com/termux-pacman/glibc-packages/assets/13085785/bb5c0842-48e1-4f70-adc0-ba525fffd72a)

testmprotect.c
`#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <malloc.h>
#include <sys/mman.h>

static void domp( void *, long );

static void domp( void *pmem, long psz ) {
    if (mprotect( pmem, psz, PROT_READ | PROT_WRITE | PROT_EXEC ) == -1) {
       perror( "mprotect failed" );
    } else {
       printf( "mprotect success\n" );
    }
}

int main( int argc, char *argv[] ) {
    long lpsz;
    void *lmem;

    lpsz = sysconf(_SC_PAGESIZE);
    printf( "Page size is %ld\n", lpsz );

    if ((lmem = memalign( lpsz, lpsz )) == NULL) {
       perror( "memalign failed" );
       exit (-1);
    }
    printf( "Memory allocated by memalign() at %p\n", lmem );
    domp( lmem, lpsz );

    return 0;
}
`

### System information

termux-info:
```
```

**Comment by szllzs** [comment]
Remove the execution flag to modify it like this, in some cases it doesn't work, if I just want to write part of the dynamically recompiled code to memory, there is a problem, SIGSEGV with Access error

**Comment by Maxython** [comment]
I studied some points in this case and I can assume that the problem here is most likely not in `mprotect` but in the memory address. So I understand that `glibc` creates such memory addresses that as a result `selinux` gives not full access to memory, and because of this, the `mprotect` error occurs.

Most likely I need help if I do not find the exact cause of this error.

**Comment by szllzs** [comment]
> I studied some points in this case and I can assume that the problem here is most likely not in `mprotect` but in the memory address. So I understand that `glibc` creates such memory addresses that as a result `selinux` gives not full access to memory, and because of this, the `mprotect` error occurs.
> 
> Most likely I need help if I do not find the exact cause of this error.

From the screenshot above, the memory address area allocated by Termux Native and the memory address allocated by Glibc for Termux do not seem to be the same
