### ISSUE TITLE
[Bug]: there is something wrong with the last update.

### ISSUE THREAD

**Issue by dhuux** [termux-pacman/glibc-packages#54]
### Problem description

flutter and dart have been working fine. but now flutter not working because dart is having problems with glibc. especially libc.so.6, i don't know. i think this happened aftet i updated with pacman. 

when it was working 
![Screenshot_20230717-025132_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/38c0c703-35aa-4171-a867-676cf1728047)

now
![Screenshot_20230721-163746_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/ea515751-f5d9-4542-b396-8cde20dd911b)
![Screenshot_20230721-163804_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/674be324-fa29-4a00-a744-54702b3a108d)

### System information

termux-info:
```
```

**Comment by Maxython** [comment]
Perhaps this problem arose due to #50.

I'm already trying to fix this wrong patch - #52.

**Comment by dhuux** [comment]
yes, that is what broke it. when will we expect the next update?

**Comment by dhuux** [comment]
i replaced libc.so.6 with one i extracted from the previous release. it seems that fixed for me.

**Comment by Maxython** [comment]
Replacing `libc.so.6` from a pre-latest version of `glibc` is not a fix for this problem

**Comment by dhuux** [comment]
it really did. the monent i replaced it. the error is gone.  i couldn't run flutter or dart before. if you see dart's crash report's last line. i suspected that and when i replaced, dart is not crashing anymore. i'm using glibc based dart with flutter. not the Termux one.

![20230722_214448](https://github.com/termux-pacman/glibc-packages/assets/63465816/050fb3f0-1f83-4a0c-b55f-1e3f00ff5b29)

**Comment by dhuux** [comment]
but the weird thing is all my glibc based programs that i patched were fine with libc.so.6 of the latest update and working fine. it was only dart that complained about it and it did work when replaced with the from your previous release. but i didn't mean it fixes `mprotect` problem.

**Comment by Maxython** [comment]
When I said that this doesn't solve the problem, I mean that installing the old glibc is not the way to solve the problem in this case. That's why I reopened your issue.

**Comment by dhuux** [comment]
i only replaced that one shared object with the one from glibc 2.36. and don't remove it. i moved it to my home dir. just in case. 
![Screenshot_20230722-233245_Termux](https://github.com/termux-pacman/glibc-packages/assets/63465816/4f6682ae-b4de-446c-8a1d-9936cee83a1f)

clearly dart have a problem with that one object. so  i considered this as a temporary solution until your fix update comes. but if there is other solution i can put it back.

thanks.

**Comment by susandahal** [comment]
This issue still persist with latest update of glibc

**Comment by susandahal** [comment]
![Uploading Screenshot_20230727-113052_Termux.png…]()
