### ISSUE TITLE
DNS?

### ISSUE THREAD

**Issue by m3t4f1v3** [termux-pacman/glibc-packages#6]
Attempting to connect to an ip via its domain name errors, however using it's pre-resolved ip works perfectly.
It seems that in the case of curl, it is trying to open /etc/nsswitch.conf, which it does not have permission to.

**Comment by Maxython** [comment]
Can you show me what is the error when using `curl` and how do you run `curl`?

I would also like to know which curl you are using: from `gpkg-dev` (compiled on a linux distribution) or from `gpkg` (compiled on termux).

**Comment by Maxython** [comment]
May I ask what architecture your device has?

**Comment by Maxython** [comment]
To resolve this issue, run the following commands:
```bash
ln -s $PREFIX/etc/resolv.conf $PREFIX/glibc/etc
ln -s $PREFIX/etc/tls/cert.pem $PREFIX/glibc/etc/ssl/certs/ca-certificates.crt
```

If the problem persists after that, then try updating `curl` using the `gpkg-dev` repo. Note: this repo contains packages that were compiled on a linux distribution, so use `proot` during the upgrade.
