### ISSUE TITLE
[Bug]: Illegal Instruction crash

### ISSUE THREAD

**Issue by susandahal** [termux-pacman/glibc-packages#77]
### Problem description

Got this issue while running flutter doctor.
This issue seem to appear randomly. It does work few times and gives this error other times

![Screenshot_20230815-131159_Termux](https://github.com/termux-pacman/glibc-packages/assets/37948853/51ce2528-b691-4253-91c0-f1e3079af570)

### System information

termux-info:
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=1298
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Usage = All
Server = https://service.termux-pacman.dev/main/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/main/aarch64
[x11]
Usage = All
Server = https://service.termux-pacman.dev/x11/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/x11/aarch64
[root]
Usage = All
Server = https://service.termux-pacman.dev/root/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/root/aarch64
[tur]
Usage = All
Server = https://service.termux-pacman.dev/tur/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur/aarch64
[tur-continuous]
Usage = All
Server = https://service.termux-pacman.dev/tur-continuous/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-continuous/aarch64
[tur-multilib]
Usage = All
Server = https://service.termux-pacman.dev/tur-multilib/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-multilib/aarch64
[gpkg-dev]
Usage = All
Server = https://service.termux-pacman.dev/gpkg-dev/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/gpkg-dev/aarch64
Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
13
Kernel build information:
Linux localhost 4.14.206-perf+ #1 SMP PREEMPT Sun Aug 13 20:01:11 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO X3 NFC
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=
```

**Comment by Maxython** [comment]
> Got this issue while running flutter doctor.
This issue seem to appear randomly. It does work few times and gives this error other times

That is, it sometimes fully works, and sometimes it gives this error? It's rather strange, but I have my suspicions why this is happening.

Were there such cases in the old version of glibc? If no, then most likely it comes from the mprotect patch (#60). But to make sure that this is what is happening, I need a log file from strace, so run the following command and send the log file:
```
strace -o file.log flutter doctor -v
```

**Comment by susandahal** [comment]
> > Got this issue while running flutter doctor.
> > This issue seem to appear randomly. It does work few times and gives this error other times
> 
> That is, it sometimes fully works, and sometimes it gives this error? It's rather strange, but I have my suspicions why this is happening.
> 
> Were there such cases in the old version of glibc? If no, then most likely it comes from 

> the mprotect patch (#60). But to make sure that this is what is happening, I need a log file from strace, so run the following command and send the log file:

> 
> ```
> strace -o file.log flutter doctor -v
> ```

Yes it works properly sometimes and i get the error sometimes

Here is the strace:-
[file.log](https://github.com/termux-pacman/glibc-packages/files/12343417/file.log)

**Comment by susandahal** [comment]
It should be glibc because it didn't work without this glibc packages.

We had to patch flutter and other elf binaries to change rpath and interpreter for it to work

**Comment by Maxython** [comment]
> It should be glibc because it didn't work without this glibc packages.
> 
> We had to patch flutter and other elf binaries to change rpath and interpreter for it to work

I rechecked the log file and your screenshot and everything points to flutter being based on bionic, but to be completely sure what it is based on run the following command:
```
file *path_to_flutter*
```

**Comment by Maxython** [comment]
> flutter is just a bash script file. So it was caused by flutter being bionic? But flutter works without any intervention in Linux so shouldn't it be based on glibc?. I also patched flutter to work with glibc libs and interpreter

Okay, I got you. Sorry that I didn’t understand right away, I didn’t immediately understand that this is a bash script. I rechecked the log file and found a binary based on glibc. Run the following command and upload another log file:
```
strace -o file.log /data/data/com.termux/files/home/.local/share/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev doctor -v
```

**Comment by susandahal** [comment]
But there is no dart doctor command. It fails with no command found.
